'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Download } from 'lucide-react';
import { downloadWPTheme } from '@/lib/wpThemeGenerator';

export default function StylePreview({ style, onClose }) {
  const [activeTab, setActiveTab] = useState('preview');
  const [downloading, setDownloading] = useState(false);

  if (!style) return null;

  const cssVariables = `/* ${style.name} - Generated by VibeSync */
:root {
  --primary-color: ${style.primaryColor};
  --secondary-color: ${style.secondaryColor};
  --accent-color: ${style.accentColor};
  --background-color: ${style.backgroundColor};
  --text-color: ${style.textColor};
  --font-family: ${style.fontFamily};
  --border-radius: ${style.borderRadius};
  --shadow-style: ${style.shadowStyle};
  --gradient-style: ${style.gradientStyle || `linear-gradient(135deg, ${style.primaryColor}, ${style.secondaryColor})`};
}

/* Apply to your project */
body {
  font-family: var(--font-family);
  background-color: var(--background-color);
  color: var(--text-color);
}

.button-primary {
  background: var(--gradient-style);
  color: white;
  padding: 12px 24px;
  border-radius: var(--border-radius);
  box-shadow: var(--shadow-style);
}

.card {
  background: white;
  border-radius: var(--border-radius);
  box-shadow: var(--shadow-style);
  padding: 24px;
}`;

  const handleExportWPTheme = async () => {
    try {
      setDownloading(true);
      await downloadWPTheme(style);
      setTimeout(() => setDownloading(false), 1000);
    } catch (error) {
      console.error('Failed to export WordPress theme:', error);
      alert('Failed to export theme. Please try again.');
      setDownloading(false);
    }
  };

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"
        onClick={onClose}
      >
        <motion.div
          initial={{ scale: 0.9, y: 20 }}
          animate={{ scale: 1, y: 0 }}
          exit={{ scale: 0.9, y: 20 }}
          className="bg-white rounded-3xl shadow-2xl w-full max-w-4xl max-h-[90vh] overflow-hidden flex flex-col"
          onClick={(e) => e.stopPropagation()}
        >
          {/* Header */}
          <div className="flex items-center justify-between p-6 border-b border-slate-200">
            <div>
              <h2 className="text-2xl font-bold text-slate-900">{style.name}</h2>
              <p className="text-sm text-slate-500 mt-1">{style.category} style</p>
            </div>
            <button
              onClick={onClose}
              className="p-2 rounded-full hover:bg-slate-100 transition-colors"
            >
              <X size={24} />
            </button>
          </div>

          {/* Tabs */}
          <div className="flex border-b border-slate-200">
            <button
              onClick={() => setActiveTab('preview')}
              className={`flex-1 px-6 py-3 font-medium transition-colors ${
                activeTab === 'preview'
                  ? 'text-violet-600 border-b-2 border-violet-600'
                  : 'text-slate-500 hover:text-slate-700'
              }`}
            >
              Preview UI
            </button>
            <button
              onClick={() => setActiveTab('css')}
              className={`flex-1 px-6 py-3 font-medium transition-colors ${
                activeTab === 'css'
                  ? 'text-violet-600 border-b-2 border-violet-600'
                  : 'text-slate-500 hover:text-slate-700'
              }`}
            >
              Get CSS
            </button>
          </div>

          {/* Content */}
          <div className="flex-1 overflow-y-auto p-6">
            {activeTab === 'preview' ? (
              <div
                className="rounded-2xl p-8 min-h-[400px]"
                style={{
                  background: style.gradientStyle || `linear-gradient(135deg, ${style.primaryColor}, ${style.secondaryColor})`,
                  fontFamily: style.fontFamily,
                }}
              >
                {/* Mock Landing Page Hero */}
                <div className="max-w-3xl mx-auto text-center">
                  <h1 className="text-5xl font-bold mb-6" style={{ color: '#ffffff' }}>
                    Welcome to Your Site
                  </h1>
                  <p className="text-xl mb-8" style={{ color: 'rgba(255,255,255,0.9)' }}>
                    Experience the perfect blend of design and functionality with this beautiful style.
                  </p>
                  <div className="flex gap-4 justify-center">
                    <button
                      className="px-8 py-4 font-semibold text-white transition-transform hover:scale-105"
                      style={{
                        backgroundColor: style.accentColor,
                        borderRadius: style.borderRadius,
                        boxShadow: style.shadowStyle,
                      }}
                    >
                      Get Started
                    </button>
                    <button
                      className="px-8 py-4 font-semibold transition-transform hover:scale-105"
                      style={{
                        backgroundColor: 'rgba(255,255,255,0.2)',
                        color: '#ffffff',
                        borderRadius: style.borderRadius,
                        border: '2px solid rgba(255,255,255,0.3)',
                      }}
                    >
                      Learn More
                    </button>
                  </div>

                  {/* Feature Cards */}
                  <div className="grid grid-cols-3 gap-6 mt-12">
                    {[1, 2, 3].map((i) => (
                      <div
                        key={i}
                        className="p-6 transition-transform hover:scale-105"
                        style={{
                          backgroundColor: 'rgba(255,255,255,0.15)',
                          backdropFilter: 'blur(10px)',
                          borderRadius: style.borderRadius,
                          border: '1px solid rgba(255,255,255,0.2)',
                        }}
                      >
                        <div
                          className="w-12 h-12 mx-auto mb-4"
                          style={{
                            backgroundColor: style.accentColor,
                            borderRadius: style.borderRadius,
                          }}
                        />
                        <h3 className="text-lg font-semibold mb-2 text-white">
                          Feature {i}
                        </h3>
                        <p className="text-sm" style={{ color: 'rgba(255,255,255,0.8)' }}>
                          Amazing feature description
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            ) : (
              <div>
                <div className="flex items-center justify-between mb-4">
                  <p className="text-sm text-slate-600">
                    Copy this CSS to use in your project:
                  </p>
                  <button
                    onClick={() => {
                      navigator.clipboard.writeText(cssVariables);
                      alert('CSS copied to clipboard!');
                    }}
                    className="px-4 py-2 text-sm font-medium text-white bg-violet-600 rounded-lg hover:bg-violet-700 transition-colors"
                  >
                    Copy All
                  </button>
                </div>
                <pre className="bg-slate-900 text-slate-100 p-6 rounded-xl overflow-x-auto text-sm font-mono">
                  {cssVariables}
                </pre>
              </div>
            )}
          </div>

          {/* Footer Actions */}
          <div className="p-6 border-t border-slate-200 bg-slate-50">
            <button
              onClick={handleExportWPTheme}
              disabled={downloading}
              className="w-full flex items-center justify-center gap-2 px-6 py-3 text-white font-semibold bg-gradient-to-r from-violet-600 to-fuchsia-600 rounded-xl hover:shadow-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <Download size={20} />
              {downloading ? 'Generating...' : 'Export as WordPress Theme'}
            </button>
            <p className="text-xs text-slate-500 text-center mt-2">
              Downloads a ready-to-use WordPress theme .zip file
            </p>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}