import JSZip from 'jszip';

export async function downloadWPTheme(style) {
  const zip = new JSZip();
  
  // Generate style.css
  const styleCSS = `/*
Theme Name: ${style.name}
Theme URI: https://vibesync.app
Author: VibeSync
Author URI: https://vibesync.app
Description: A custom WordPress theme generated from VibeSync - ${style.category} style
Version: 1.0
License: GNU General Public License v2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
Text Domain: ${style.name.toLowerCase().replace(/\s+/g, '-')}
*/

:root {
  --primary-color: ${style.primaryColor};
  --secondary-color: ${style.secondaryColor};
  --accent-color: ${style.accentColor};
  --background-color: ${style.backgroundColor};
  --text-color: ${style.textColor};
  --font-family: ${style.fontFamily};
  --border-radius: ${style.borderRadius};
  --shadow-style: ${style.shadowStyle};
}

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: var(--font-family);
  background-color: var(--background-color);
  color: var(--text-color);
  line-height: 1.6;
}

a {
  color: var(--primary-color);
  text-decoration: none;
  transition: color 0.3s ease;
}

a:hover {
  color: var(--accent-color);
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 20px;
}

header {
  background: ${style.gradientStyle || `linear-gradient(135deg, ${style.primaryColor}, ${style.secondaryColor})`};
  padding: 20px 0;
  box-shadow: var(--shadow-style);
}

header .site-title {
  color: white;
  font-size: 2rem;
  font-weight: bold;
}

nav ul {
  list-style: none;
  display: flex;
  gap: 20px;
}

nav a {
  color: white;
  padding: 10px 20px;
  border-radius: var(--border-radius);
  transition: background 0.3s ease;
}

nav a:hover {
  background: rgba(255, 255, 255, 0.2);
}

.content {
  padding: 40px 0;
}

.post {
  background: white;
  padding: 30px;
  margin-bottom: 30px;
  border-radius: var(--border-radius);
  box-shadow: var(--shadow-style);
}

.post-title {
  color: var(--primary-color);
  font-size: 2rem;
  margin-bottom: 15px;
}

.button,
input[type="submit"] {
  background-color: var(--accent-color);
  color: white;
  padding: 12px 30px;
  border: none;
  border-radius: var(--border-radius);
  cursor: pointer;
  font-size: 1rem;
  transition: transform 0.2s ease, box-shadow 0.2s ease;
}

.button:hover,
input[type="submit"]:hover {
  transform: translateY(-2px);
  box-shadow: var(--shadow-style);
}

footer {
  background: var(--secondary-color);
  color: var(--text-color);
  padding: 30px 0;
  text-align: center;
  margin-top: 40px;
}
`;

  // Generate index.php
  const indexPHP = `<?php
/**
 * Main template file
 * Generated by VibeSync
 */
get_header();
?>

<div class="container">
  <main class="content">
    <?php
    if (have_posts()) :
      while (have_posts()) : the_post();
    ?>
        <article id="post-<?php the_ID(); ?>" <?php post_class('post'); ?>>
          <h2 class="post-title">
            <a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
          </h2>
          <div class="post-meta">
            <span>By <?php the_author(); ?></span> | 
            <span><?php the_date(); ?></span>
          </div>
          <div class="post-content">
            <?php the_excerpt(); ?>
          </div>
          <a href="<?php the_permalink(); ?>" class="button">Read More</a>
        </article>
    <?php
      endwhile;
    else :
    ?>
      <p>No posts found.</p>
    <?php
    endif;
    ?>
  </main>
</div>

<?php get_footer(); ?>
`;

  // Generate header.php
  const headerPHP = `<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
  <meta charset="<?php bloginfo('charset'); ?>">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php wp_title('|', true, 'right'); bloginfo('name'); ?></title>
  <?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>

<header>
  <div class="container">
    <h1 class="site-title">
      <a href="<?php echo esc_url(home_url('/')); ?>" style="color: white;">
        <?php bloginfo('name'); ?>
      </a>
    </h1>
    <p style="color: rgba(255,255,255,0.9);"><?php bloginfo('description'); ?></p>
    <nav>
      <?php
      wp_nav_menu(array(
        'theme_location' => 'primary',
        'container' => false,
        'fallback_cb' => false
      ));
      ?>
    </nav>
  </div>
</header>
`;

  // Generate footer.php
  const footerPHP = `<footer>
  <div class="container">
    <p>&copy; <?php echo date('Y'); ?> <?php bloginfo('name'); ?>. All rights reserved.</p>
    <p>Theme generated by <a href="https://vibesync.app" style="color: inherit;">VibeSync</a></p>
  </div>
</footer>

<?php wp_footer(); ?>
</body>
</html>
`;

  // Generate functions.php
  const functionsPHP = `<?php
/**
 * Theme functions and definitions
 * Generated by VibeSync
 */

// Enqueue styles
function vibesync_theme_styles() {
  wp_enqueue_style('vibesync-style', get_stylesheet_uri());
}
add_action('wp_enqueue_scripts', 'vibesync_theme_styles');

// Theme support
function vibesync_theme_support() {
  add_theme_support('title-tag');
  add_theme_support('post-thumbnails');
  add_theme_support('custom-logo');
  add_theme_support('html5', array('search-form', 'comment-form', 'comment-list', 'gallery', 'caption'));
  
  // Register navigation menu
  register_nav_menus(array(
    'primary' => __('Primary Menu', 'vibesync')
  ));
}
add_action('after_setup_theme', 'vibesync_theme_support');

// Widget areas
function vibesync_widgets_init() {
  register_sidebar(array(
    'name' => __('Sidebar', 'vibesync'),
    'id' => 'sidebar-1',
    'before_widget' => '<div class="widget">',
    'after_widget' => '</div>',
    'before_title' => '<h3 class="widget-title">',
    'after_title' => '</h3>',
  ));
}
add_action('widgets_init', 'vibesync_widgets_init');
?>
`;

  // Add files to zip
  zip.file('style.css', styleCSS);
  zip.file('index.php', indexPHP);
  zip.file('header.php', headerPHP);
  zip.file('footer.php', footerPHP);
  zip.file('functions.php', functionsPHP);

  // Generate and download
  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${style.name.toLowerCase().replace(/\s+/g, '-')}-wp-theme.zip`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}